# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and Release

on:
  push:
    tags: []

jobs:
  build:
    strategy:
      matrix:
        arch: [x64]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Install NSIS
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis
    - name: Install OpenCV
      # if: matrix.dep == 'with-opencv'
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install -y opencv
    - name: Add opencv to path
      # if: matrix.dep == 'with-opencv'
      run: echo "c:\tools\opencv\build\x64\vc16\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Configure CMake Debug
      run: >
        cmake -B ${{github.workspace}}/build
        -A${{matrix.arch}}
        -DARCH=${{matrix.arch}}
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_PREFIX_PATH=c:\tools\opencv\build\x64\vc16\lib
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install_debug
    - name: Build and Install Debug
      run: cmake --build ${{github.workspace}}/build --config Debug -t install
    - name: Configure CMake Release
      run: >
        cmake -B ${{github.workspace}}/build
        -A${{matrix.arch}}
        -DARCH=${{matrix.arch}}
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_PREFIX_PATH=c:\tools\opencv\build\x64\vc16\lib
        -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install_release
    - name: Build and Install Release
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Create NSIS Package
      working-directory: ${{github.workspace}}/build
      run: cpack -G NSIS
    - uses: actions/upload-artifact@v3
      with:
        name: nsis-${{matrix.arch}}
        path: ${{github.workspace}}/build/WebCFace-*-${{matrix.arch}}.exe
  
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: nsis-Win32
      #     path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v3
        with:
          name: nsis-x64
          path: ${{github.workspace}}/artifact
      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: artifact/*
