# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build and Release

on:
  push:
    tags: []

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        arch: [Win32, x64]
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
    - name: Install NSIS
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis
    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -A${{matrix.arch}}
        -DARCH=${{matrix.arch}}
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Create NSIS Package
      working-directory: ${{github.workspace}}/build
      run: cpack -G NSIS
    - uses: actions/upload-artifact@v3
      with:
        name: nsis-${{matrix.arch}}
        path: ${{github.workspace}}/build/WebCFace-*-${{matrix.arch}}.exe
  
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: nsis-Win32
          path: ${{github.workspace}}/artifact
      - uses: actions/download-artifact@v3
        with:
          name: nsis-x64
          path: ${{github.workspace}}/artifact
      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: artifact/*
